codestates-seb/seb43_main_027

client/src/App.tsx

init: 테스트를 위한 코드 변경

---

client/src/App.tsx

:bug: fix: 머지 충돌 해결

---

server/inddybuddy/src/main/java/codejejus/inddybuddy/game/GameController.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/game/GameService.java

long을 Long으로 변경
modifyGame 카테고리 변경 수정
method refactoring

refactor : GameService refactoring

---

client/src/App.tsx
client/src/index.tsx
client/src/layouts/Header/Header.tsx
client/src/layouts/Header/HeaderBtn.tsx
client/src/layouts/Header/HeaderBtnContainer.tsx
client/src/layouts/Header/Logo.tsx
client/src/layouts/Header/MenuBtn.tsx
client/src/layouts/Header/SearchBar.tsx
client/src/layouts/Header/SearchHint.tsx
client/src/layouts/Header/UserBtn.tsx
client/src/slice/userSlice.ts
client/src/store/store.ts
client/src/styles/globalStyles.js

- 헤더 작업
- redux 초기 세팅 및 유저 슬라이스 추가
- index.tsx에 BrowserRouter, Provider 추가
- App.tsx에 헤더 컴포넌트 추가

Fe feat/헤더

---

server/inddybuddy/src/main/java/codejejus/inddybuddy/game/GameService.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/post/Post.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostController.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostDto.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostMapper.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostRepository.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostService.java

post entity, Controller, dto, mapper, repository, service 작성
게시글 작성 기능 구현

feat : Post Entity 및 Create 완료

---

client/src/App.tsx
client/src/layouts/CategoryGames/RecommendGames.tsx
client/src/layouts/Footer/Footer.tsx
client/src/layouts/Footer/Member.tsx
client/src/layouts/Header/Logo.tsx
client/src/layouts/Nav/Nav.tsx
client/src/pages/CategoryGames.tsx
client/src/pages/Template.tsx
client/src/types/propsTypes.ts

- 푸터 컴포넌트 구현
- 템플릿 페이지 컴포넌트 추가
- 기본 라우터 컴포넌트 적용

✨ 푸터 컴포넌트 구현 완료

---

client/src/data/dummyCategories.ts
client/src/layouts/CategoryGames/FilterTap.tsx
client/src/layouts/CategoryGames/GameItem.tsx
client/src/layouts/CategoryGames/GameList.tsx
client/src/layouts/CategoryGames/MainContainer.tsx
client/src/layouts/CategoryGames/RecommendGames.tsx
client/src/layouts/CategoryGames/TitleCategory.tsx
client/src/pages/CategoryGames.tsx
client/src/styles/globalStyles.js

Fe feat/카테고리 페이지

---

server/inddybuddy/src/main/java/codejejus/inddybuddy/global/config/SecurityConfig.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/global/jwt/JwtTokenProvider.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/global/jwt/filter/JwtExceptionFilter.java

feat : JWT 예외 처리 기능 추가

---

server/inddybuddy/src/main/java/codejejus/inddybuddy/post/Post.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostController.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostMapper.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostService.java

feat : 게시글 삭제 기능

---

client/src/components/common/CategoryCard.tsx
client/src/components/common/GameCard.tsx
client/src/components/common/PostItem.tsx
client/src/components/ui/Badge.tsx
client/src/data/categoryIcons.tsx
client/src/hooks/useFetch.ts
client/src/layouts/Home/CategoryContainer.tsx
client/src/layouts/Nav/UserNavItem.tsx
client/src/types/dataTypes.ts

- 홈 카테고리 별 아이콘 추가
- 네비게이션바 기능 구현

✨ 홈-카테고리 기능 추가

---

client/src/layouts/Nav/NavContent.tsx

추후 기능 구현에 대해 수정이 있을 수 있습니다! 그 부분은 서버 통신을 좀 더 완벽하게 확인한 뒤 수정에 들어갈 것입니다.

Fe feat/네비게이션 기능

---

client/src/App.tsx
client/src/components/CategoryGames/GameItem.tsx
client/src/components/CategoryGames/GameList.tsx
client/src/components/CategoryGames/RecommendGames.tsx
client/src/constants/pathUrl.ts
client/src/constants/stringMessage.ts
client/src/types/dataTypes.ts

- 데이터패칭시 응답에 담긴 페이지네이션 사용 (추후 페이지네이션, 필터링 read테스트 필요할듯)
- 로그인한 유저의 게임 팔로우 목록 조회

Fe fect/게임채널

---

client/src/AppRoutes.tsx
client/src/components/Home/FilterBar.tsx
client/src/components/Home/GameContainer.tsx
client/src/components/Home/HomeGameCard.tsx
client/src/components/Posting/ImageSection.tsx
client/src/components/Posting/InputSection.tsx
client/src/components/common/GameCard.tsx
client/src/constants/pathUrl.ts
client/src/layouts/Nav/NavContent.tsx
client/src/pages/LogIn/LogIn.tsx
client/src/pages/SignUp/SignUp.tsx
client/src/types/dataTypes.ts
client/src/utils/postingValidate.ts
client/src/utils/validatePost.ts

- 입력값 검사 
- 태그가 선택되었는지 / 내용이 있는지 / 제목의 길이가 5 이상인지
- 이미지 폼데이터로 변경 후 서버에 전송

✨ 게시글 작성페이지 기능 구현

---

client/src/App.tsx
client/src/AppRoutes.tsx
client/src/constants/pathUrl.ts

- 새로 고침 시 유저 로그인 되도록 기능 구현
- 게시글 작성 페이지 경로 수정

🐛 Fe fix/유저상태관리

---

client/src/components/CategoryGames/RecommendGames.tsx
client/src/components/GameChannel/GameTitle.tsx
client/src/components/GameChannel/PostList.tsx
client/src/hooks/useValidation.ts

카테고리페이지, 게임채널 페이지 수정 합본입니다.
마이페이지 작업은 추가될 예정입니다.

Fe feat/마이페이지

---

client/src/api/apiCollection.ts
client/src/components/Home/GameContainer.tsx
client/src/components/Home/HomeGameCard.tsx
client/src/components/Posting/InputSection.tsx
client/src/components/Posts/CommentInput.tsx
client/src/components/Posts/CommentItem.tsx
client/src/components/Posts/CommentSection.tsx
client/src/components/Posts/PostInfo.tsx
client/src/components/Posts/ReCommentInput.tsx
client/src/components/Posts/Reaction.tsx
client/src/components/UserInfo/UserActions.tsx
client/src/components/common/GameCard.tsx
client/src/constants/pathUrl.ts
client/src/layouts/Header/Header.tsx
client/src/layouts/Header/UserBtn.tsx
client/src/layouts/Nav/NavContent.tsx
client/src/layouts/Nav/UserNavItem.tsx
client/src/pages/Posts.tsx
client/src/slice/userSlice.ts
client/src/types/dataTypes.ts

게시글 상세 페이지 1차 구현 완료
- 게시글 수정, 댓글 작성/수정, 좋아요 기능 구현 완료
- 게시글 수정 시 태그 기본값 반영
- 로그아웃 기능 구현
- 네비게이션바 로그인 되지 않은 상태에서 데이터 패칭하지 않도록 수정

✨ Fe feat/게시글상세페이지

---

client/src/components/Posts/CommentItem.tsx
client/src/components/Posts/ImageItem.tsx
client/src/components/Posts/ImageSection.tsx
client/src/components/Posts/PostInfo.tsx
client/src/components/Posts/Title.tsx
client/src/layouts/Header/UserBtn.tsx
client/src/layouts/Nav/UserNavItem.tsx
client/src/utils/validatePost.ts

- 게시글 상세 페이지 뒤로가기
- 유저 아이콘 그림자 효과
- 게시글 상세페이지 이미지 섹션 디자인 수정 열로 보이도록 수정

🎨  design: 디자인 일부 수정

---

server/inddybuddy/src/main/java/codejejus/inddybuddy/comment/Comment.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/comment/CommentController.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/comment/CommentDto.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/comment/CommentMapper.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/comment/CommentRepository.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/comment/CommentService.java
server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostMapper.java

Be feat/기능 고도화 대댓글 기능 만들기

---

client/src/pages/GameRegister.tsx

:bug: fix: 태그 최소 1개 이상 선택하도록 재수정

---

client/src/components/Home/CategoryContainer.tsx
client/src/components/Message/MessageOutput.tsx
client/src/components/Posting/InputSection.tsx
client/src/components/Posts/CommentInput.tsx
client/src/components/Posts/CommentItem.tsx
client/src/components/Posts/CommentSection.tsx
client/src/components/Posts/PostInfo.tsx
client/src/components/Posts/ReCommentInput.tsx
client/src/components/Posts/ReCommentItem.tsx
client/src/components/Posts/Title.tsx
client/src/components/common/PostItem.tsx
client/src/data/initialData.ts
client/src/layouts/Nav/Nav.tsx
client/src/layouts/Nav/NavContent.tsx
client/src/pages/Message.tsx
client/src/pages/Posts.tsx
client/src/types/dataTypes.ts

✨ 게시글상세페이지 및 부가 기능 구현

---

client/src/pages/Login.tsx
client/src/pages/Signup.tsx

:bug: fix: 에러에 따른 모달 오류 수정

---

client/src/components/Search/SearchGame.tsx
client/src/components/Search/SearchUser.tsx
client/src/components/Signup/ConfirmModal.tsx
client/src/components/Signup/SignupBtn.tsx
client/src/components/Signup/SignupConfirmModal.tsx
client/src/components/Signup/SignupFieldsContainer.tsx
client/src/components/common/InputContainer.tsx
client/src/pages/Login.tsx
client/src/pages/Signup.tsx
client/src/slice/signupValiditySlice.ts
client/src/store/store.ts
client/src/types/dataTypes.ts

✨ feat: 이메일인증기능
